language: rust

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y upx electric-fence libsdl1.2-dev

script:
  - cargo build --verbose
  - cargo test --verbose

after_success: |
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    cargo doc &&
    echo '<meta http-equiv=refresh content="0;url=tcod/index.html">' > target/doc/index.html &&
    git config --global user.email "travis@travis-ci.org" &&
    git config --global user.name "travis-ci" &&
    sudo pip install ghp-import &&
    ghp-import -n target/doc &&
    git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages

env:
    global:
        secure: b9rReQG13A38c/nr2zuv0FiAAZvDadjuH9nuRQa9mex+/vLtoqzUdlnrxzWYfX9ydP8IAEZnx2PO+GYSLEFrCo2Qn+zYXjD09Ypib/xA/ln3D3bz/gRCzilQJLaTm0Xo5Npj3pa3DcyZcpZWwe5DKhoczSvzmmFyTcvnZLNY/do=
