language: rust
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y libsdl1.2debian
  - curl -L "http://doryen.eptalys.net/?file_id=28" -o libtcod-1.5.1-linux64.tar.gz
  - tar -xzf libtcod-1.5.1-linux64.tar.gz
  - sudo cp libtcod-1.5.1/libtcod{,gui}.so /usr/lib/x86_64-linux-gnu/
script:
  - cargo build --verbose
  - cargo test --verbose
