[package]
name = "tcod"
description = "The Rust bindings for the Doryen library (a.k.a. libtcod)."
version = "0.4.2"
homepage = "https://github.com/tomassedovic/tcod-rs"
repository = "https://github.com/tomassedovic/tcod-rs"
readme = "README.md"
keywords = ["gamedev", "roguelike", "libtcod"]
license = "WTFPL"
authors = ["Tomas Sedovic <tomas@sedovic.cz>",
           "Edu Garcia <arcnorj@gmail.com>",
           "Guillermo Galizzi <galizzi.guillermo@gmail.com>",
           "@Moredread",
           "Jared McFarland <jared.online@gmail.com>",
           "Jonny Gilchrist (@jgilchrist)",
           "Paul Sanford <me@paulsanford.net>",
           "@Pranz <jesper.fridefors@gmail.com>"]

[lib]
name = "tcod"
path = "src/lib.rs"

[dependencies]
bitflags = "0.1"

[dependencies.tcod-sys]
path = "tcod-sys"
version = "2.0.0"

# TODO: temporarily disabling debuginfo until this is fixed:
# https://github.com/rust-lang/rust/issues/17257
[profile.dev]
debug = false
[profile.test]
debug = false
