[package]
name = "tcod"
version = "0.1.0"
authors = ["tomas@sedovic.cz", "arcnorj@gmail.com"]
build = "./build.sh"

[lib]

name = "tcod"
path = "src/lib.rs"

[profile.test]
# Workaround for https://github.com/rust-lang/rust/issues/17021
debug = false